[package]
name = 'wasmer-examples/winter-js-echo'
version = '0.2.0'
description = 'Javascript echo server using winter-js.'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]
"wasmer/winterjs" = "*"

[fs]
"/app" = "./app"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["serve", "/app/app.js", "--script"]